import { Inter } from "next/font/google";
import {Providers} from "@/app/providers";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsappUi from "@/components/WhatsappUi";
import "@/app/globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Providers>
      <NavBar/>
      <WhatsappUi/>
        {children}
      <Footer/>
      </Providers>
      </body>
    </html>
  );
}
